import type { PolicyClause } from "./templates";

export const CORE_POLICY_TEMPLATE_CLAUSES_VULNERABLE_CUST: PolicyClause[] = [
  {
    id: "clause-vc-purpose",
    title: "Purpose",
    summary: "Define why the vulnerable customer policy exists",
    content: "Describe how the firm identifies and supports customers in vulnerable circumstances.",
    category: "customer",
    isMandatory: true,
    appliesTo: ["VULNERABLE_CUST"],
  },
  {
    id: "clause-vc-scope",
    title: "Scope",
    summary: "Confirm who and what the policy covers",
    content: "Applies to all retail client interactions across channels.",
    category: "customer",
    isMandatory: true,
    appliesTo: ["VULNERABLE_CUST"],
  },
  {
    id: "clause-vc-definitions",
    title: "Definitions",
    summary: "Capture the FCA vulnerability drivers",
    content: "- Health\n- Life events\n- Resilience\n- Capability",
    category: "customer",
    isMandatory: true,
    appliesTo: ["VULNERABLE_CUST"],
  },
  {
    id: "clause-vc-roles",
    title: "Roles & responsibilities",
    summary: "Set governance and first/second line ownership",
    content: "Board/SMF oversight, first-line ownership, compliance monitoring.",
    category: "governance",
    isMandatory: true,
    appliesTo: ["VULNERABLE_CUST"],
  },
  {
    id: "clause-vc-flags",
    title: "Vulnerability Flagging",
    summary: "Capture disclosed vulnerabilities with consent and support preferences",
    content:
      "We maintain a central register of customer vulnerability disclosures including context, consent, and support preferences. Adjustments are recorded and reviewed quarterly.",
    category: "customer",
    isMandatory: true,
    appliesTo: ["VULNERABLE_CUST"],
  },
  {
    id: "clause-vc-adjustments",
    title: "Reasonable Adjustments",
    summary: "Set out adjustments offered to vulnerable customers",
    content:
      "Reasonable adjustments (communication formats, dedicated contacts, pace adjustments) are offered on disclosure and tracked through resolution.",
    category: "customer",
    appliesTo: ["VULNERABLE_CUST"],
  },
  {
    id: "clause-vc-communications",
    title: "Communications & accessibility",
    summary: "Record accessible formats and support routes",
    content: "Large print, TTS, BSL, language support, reasonable adjustments.",
    category: "customer",
    isMandatory: true,
    appliesTo: ["VULNERABLE_CUST"],
  },
  {
    id: "clause-vc-product-design",
    title: "Product & service design",
    summary: "Ensure product design supports fair outcomes",
    content: "Needs assessments, outcome testing, and periodic reviews.",
    category: "customer",
    isMandatory: true,
    appliesTo: ["VULNERABLE_CUST"],
  },
  {
    id: "clause-vc-mi-outcomes",
    title: "MI & outcomes",
    summary: "Define MI and outcome testing expectations",
    content: "Complaints, error rates, cancellations, support metrics, and outcome testing.",
    category: "governance",
    isMandatory: true,
    appliesTo: ["VULNERABLE_CUST"],
  },
  {
    id: "clause-vc-training",
    title: "Training & competence",
    summary: "Set induction and annual refresher expectations",
    content: "Induction, annual refreshers, and QA checks aligned to vulnerable customer obligations.",
    category: "governance",
    isMandatory: true,
    appliesTo: ["VULNERABLE_CUST"],
  },
  {
    id: "clause-vc-review",
    title: "Review & governance",
    summary: "Set review cadence, approvals, and versioning",
    content: "Review cadence, approvals, and versioning controls for ongoing governance.",
    category: "governance",
    isMandatory: true,
    appliesTo: ["VULNERABLE_CUST"],
  },
];
