import type { PolicyClause } from "./templates";

export const CORE_POLICY_TEMPLATE_CLAUSES_RISK_MGMT: PolicyClause[] = [
  {
    id: "clause-risk-purpose",
    title: "Purpose",
    summary: "Define risk management objectives",
    content: "Set how the firm identifies, assesses, mitigates, and reports risk.",
    category: "governance",
    isMandatory: true,
    appliesTo: ["RISK_MGMT"],
  },
  {
    id: "clause-risk-perimeter",
    title: "Regulatory perimeter",
    summary: "Confirm permissions, perimeter boundaries, and change triggers",
    content: "Maintain documented permission scope (PERG) with change triggers, approvals, and ongoing monitoring.",
    category: "governance",
    isMandatory: true,
    appliesTo: ["RISK_MGMT"],
  },
  {
    id: "clause-risk-appetite",
    title: "Risk appetite",
    summary: "Define risk appetite and tolerance statements",
    content: "Document risk appetite statements, thresholds, and escalation triggers.",
    category: "governance",
    isMandatory: true,
    appliesTo: ["RISK_MGMT"],
  },
  {
    id: "clause-risk-assessment",
    title: "Risk assessment process",
    summary: "Define risk identification and assessment",
    content: "Identify inherent risks, assess impact/likelihood, and define residual risk.",
    category: "operations",
    isMandatory: true,
    appliesTo: ["RISK_MGMT"],
  },
  {
    id: "clause-risk-controls",
    title: "Control framework",
    summary: "Define controls and ownership",
    content: "Document control ownership, testing, and remediation expectations.",
    category: "operations",
    isMandatory: true,
    appliesTo: ["RISK_MGMT"],
  },
  {
    id: "clause-risk-reporting",
    title: "Risk reporting",
    summary: "Define MI and reporting cadence",
    content: "Report key risks, incidents, and KRIs to senior management and the board.",
    category: "governance",
    isMandatory: true,
    appliesTo: ["RISK_MGMT"],
  },
  {
    id: "clause-risk-governance",
    title: "Governance & review",
    summary: "Define governance and review cadence",
    content: "Annual review with board oversight and evidence of changes.",
    category: "governance",
    isMandatory: true,
    appliesTo: ["RISK_MGMT"],
  },
];
