import type { PolicyClause } from "./templates";

export const CORE_POLICY_TEMPLATE_CLAUSES_SUITABILITY_ADVICE: PolicyClause[] = [
  {
    id: "clause-suit-purpose",
    title: "Purpose",
    summary: "Define why suitability of advice requirements apply",
    content: "Ensure personal recommendations are suitable and in clients' best interests.",
    category: "market",
    isMandatory: true,
    appliesTo: ["SUITABILITY_ADVICE"],
  },
  {
    id: "clause-suit-scope",
    title: "Scope & permissions",
    summary: "Confirm advisory scope and client types covered",
    content: "Advisory vs execution-only scope, permissions, and client type coverage.",
    category: "market",
    isMandatory: true,
    appliesTo: ["SUITABILITY_ADVICE"],
  },
  {
    id: "clause-suit-fact-finding",
    title: "Fact-finding & information gathering",
    summary: "Define the minimum information captured before advice",
    content: "KYC, objectives, financial situation, risk profile, and capacity for loss.",
    category: "market",
    isMandatory: true,
    appliesTo: ["SUITABILITY_ADVICE"],
  },
  {
    id: "clause-suit-assessment",
    title: "Assessment of suitability",
    summary: "Define methodology and documentation standards",
    content: "Methodology, tools (e.g., IAAT), and documentation standards.",
    category: "market",
    isMandatory: true,
    appliesTo: ["SUITABILITY_ADVICE"],
  },
  {
    id: "clause-suit-disclosure",
    title: "Disclosure & communication",
    summary: "Confirm disclosure of costs, risks, and conflicts",
    content: "Costs/charges, risks, limitations, and conflicts disclosures.",
    category: "market",
    isMandatory: true,
    appliesTo: ["SUITABILITY_ADVICE"],
  },
  {
    id: "clause-suit-reviews",
    title: "Ongoing reviews",
    summary: "Define review cadence and trigger events",
    content: "Cadence, triggers, and change-of-circumstance reviews.",
    category: "market",
    isMandatory: true,
    appliesTo: ["SUITABILITY_ADVICE"],
  },
  {
    id: "clause-suit-qa",
    title: "Quality assurance & file reviews",
    summary: "Define sampling and remediation expectations",
    content: "Sampling, grading, remediation, and MI reporting.",
    category: "governance",
    isMandatory: true,
    appliesTo: ["SUITABILITY_ADVICE"],
  },
  {
    id: "clause-suit-governance",
    title: "Governance & record keeping",
    summary: "Define approvals, versioning, and retention",
    content: "Approvals, versioning, and retention requirements.",
    category: "governance",
    isMandatory: true,
    appliesTo: ["SUITABILITY_ADVICE"],
  },
];
