import type { RiskRecord } from "./riskConstants";

export const mockRisks: RiskRecord[] = [
  {
    id: "risk-1",
    riskId: "RA-001",
    title: "Third-party payment processor outage",
    description: "Service interruption from primary payment processor leading to settlement delays and customer impact.",
    category: "operational",
    subCategory: "Third-party",
    likelihood: 4,
    impact: 4,
    residualLikelihood: 3,
    residualImpact: 3,
    velocity: "fast",
    riskOwner: "Oliver Chen",
    businessUnit: "Payments",
    process: "Settlement",
    controlCount: 5,
    controlEffectiveness: 3.6,
    status: "open",
    reviewFrequency: "monthly",
    regulatoryCategory: ["Operational Resilience", "FCA Handbook"],
    reportableToFCA: true,
    consumerDutyRelevant: true,
    keyRiskIndicators: [
      {
        id: "kri-1",
        name: "Failed Transactions",
        metric: "Count / day",
        threshold: { green: 20, amber: 40, red: 60 },
        currentValue: 32,
        direction: "up",
      },
    ],
  },
  {
    id: "risk-2",
    riskId: "RA-002",
    title: "Financial crime monitoring gaps",
    description: "Inconsistent tuning of AML scenarios increasing false positives and risk of undetected suspicious activity.",
    category: "compliance",
    subCategory: "Financial Crime",
    likelihood: 3,
    impact: 5,
    residualLikelihood: 2,
    residualImpact: 4,
    velocity: "medium",
    riskOwner: "Regina Miles",
    businessUnit: "Compliance",
    process: "AML Monitoring",
    controlCount: 8,
    controlEffectiveness: 4,
    status: "under_review",
    reviewFrequency: "quarterly",
    regulatoryCategory: ["Financial Crime", "SMCR"],
    reportableToFCA: false,
    consumerDutyRelevant: false,
    keyRiskIndicators: [
      {
        id: "kri-2",
        name: "SAR Submissions",
        metric: "Count / month",
        threshold: { green: 5, amber: 10, red: 15 },
        currentValue: 11,
        direction: "up",
      },
      {
        id: "kri-3",
        name: "PEP Matches",
        metric: "Count",
        threshold: { green: 2, amber: 5, red: 10 },
        currentValue: 4,
        direction: "steady",
      },
    ],
  },
  {
    id: "risk-3",
    riskId: "RA-003",
    title: "Consumer duty communications",
    description: "Potential for unclear customer communications creating poor outcomes for vulnerable customers.",
    category: "conduct",
    subCategory: "Customer Communications",
    likelihood: 2,
    impact: 4,
    residualLikelihood: 2,
    residualImpact: 3,
    velocity: "medium",
    riskOwner: "Sasha Patel",
    businessUnit: "Customer Experience",
    process: "Communications",
    controlCount: 6,
    controlEffectiveness: 3,
    status: "mitigated",
    reviewFrequency: "semi-annually",
    regulatoryCategory: ["Consumer Duty"],
    reportableToFCA: false,
    consumerDutyRelevant: true,
    keyRiskIndicators: [
      {
        id: "kri-4",
        name: "Customer Complaints",
        metric: "Count / month",
        threshold: { green: 15, amber: 30, red: 45 },
        currentValue: 18,
        direction: "down",
      },
    ],
  },
];
