import type { RiskRecord } from "./riskConstants";

export const mockRisks: RiskRecord[] = [
  {
    id: "risk-1",
    riskId: "RA-001",
    title: "Third-party payment processor outage",
    description: "Service interruption from primary payment processor leading to settlement delays and customer impact.",
    category: "operational",
    subCategory: "Third-party",
    likelihood: 4,
    impact: 4,
    residualLikelihood: 3,
    residualImpact: 3,
    velocity: "fast",
    riskOwner: "Oliver Chen",
    businessUnit: "Payments",
    process: "Settlement",
    controlCount: 5,
    controlEffectiveness: 3.6,
    status: "open",
    reviewFrequency: "monthly",
    regulatoryCategory: ["Operational Resilience", "FCA Handbook"],
    reportableToFCA: true,
    consumerDutyRelevant: true,
    keyRiskIndicators: [
      {
        id: "kri-1",
        name: "Failed Transactions",
        metric: "Count / day",
        threshold: { green: 20, amber: 40, red: 60 },
        currentValue: 32,
        direction: "up",
      },
    ],
  },
  {
    id: "risk-2",
    riskId: "RA-002",
    title: "Financial crime monitoring gaps",
    description: "Inconsistent tuning of AML scenarios increasing false positives and risk of undetected suspicious activity.",
    category: "compliance",
    subCategory: "Financial Crime",
    likelihood: 3,
    impact: 5,
    residualLikelihood: 2,
    residualImpact: 4,
    velocity: "medium",
    riskOwner: "Regina Miles",
    businessUnit: "Compliance",
    process: "AML Monitoring",
    controlCount: 8,
    controlEffectiveness: 4,
    status: "under_review",
    reviewFrequency: "quarterly",
    regulatoryCategory: ["Financial Crime", "SMCR"],
    reportableToFCA: false,
    consumerDutyRelevant: false,
    keyRiskIndicators: [
      {
        id: "kri-2",
        name: "SAR Submissions",
        metric: "Count / month",
        threshold: { green: 5, amber: 10, red: 15 },
        currentValue: 11,
        direction: "up",
      },
      {
        id: "kri-3",
        name: "PEP Matches",
        metric: "Count",
        threshold: { green: 2, amber: 5, red: 10 },
        currentValue: 4,
        direction: "steady",
      },
    ],
  },
  {
    id: "risk-3",
    riskId: "RA-003",
    title: "Consumer duty communications",
    description: "Potential for unclear customer communications creating poor outcomes for vulnerable customers.",
    category: "conduct",
    subCategory: "Customer Communications",
    likelihood: 2,
    impact: 4,
    residualLikelihood: 2,
    residualImpact: 3,
    velocity: "medium",
    riskOwner: "Sasha Patel",
    businessUnit: "Customer Experience",
    process: "Communications",
    controlCount: 6,
    controlEffectiveness: 3,
    status: "mitigated",
    reviewFrequency: "semi-annually",
    regulatoryCategory: ["Consumer Duty"],
    reportableToFCA: false,
    consumerDutyRelevant: true,
    keyRiskIndicators: [
      {
        id: "kri-4",
        name: "Customer Complaints",
        metric: "Count / month",
        threshold: { green: 15, amber: 30, red: 45 },
        currentValue: 18,
        direction: "down",
      },
    ],
  },
  {
    id: "risk-complaints-1",
    riskId: "RA-020",
    title: "Missed complaint timelines",
    description: "Failure to meet DISP/PSR timelines leading to customer detriment and regulatory scrutiny.",
    category: "conduct",
    subCategory: "Complaints",
    likelihood: 3,
    impact: 4,
    residualLikelihood: 2,
    residualImpact: 3,
    velocity: "medium",
    riskOwner: "Complaints Manager",
    businessUnit: "Customer Operations",
    process: "Complaints handling",
    controlCount: 5,
    controlEffectiveness: 3.2,
    status: "open",
    reviewFrequency: "monthly",
    regulatoryCategory: ["DISP", "PSR"],
    reportableToFCA: false,
    consumerDutyRelevant: true,
    keyRiskIndicators: [
      {
        id: "kri-complaints-1",
        name: "Final responses on time",
        metric: "% within SLA",
        threshold: { green: 95, amber: 90, red: 85 },
        currentValue: 88,
        direction: "down",
      },
    ],
  },
  {
    id: "risk-complaints-2",
    riskId: "RA-021",
    title: "Escalation or forwarding failure",
    description: "Complaints not escalated or forwarded correctly, causing delays and customer harm.",
    category: "operational",
    subCategory: "Third-party",
    likelihood: 3,
    impact: 3,
    residualLikelihood: 2,
    residualImpact: 2,
    velocity: "medium",
    riskOwner: "Third Party Oversight Lead",
    businessUnit: "Operations",
    process: "Complaint forwarding",
    controlCount: 3,
    controlEffectiveness: 3.5,
    status: "open",
    reviewFrequency: "quarterly",
    regulatoryCategory: ["DISP"],
    reportableToFCA: false,
    consumerDutyRelevant: true,
    keyRiskIndicators: [
      {
        id: "kri-complaints-2",
        name: "Forwarding within SLA",
        metric: "% within SLA",
        threshold: { green: 98, amber: 95, red: 90 },
        currentValue: 96,
        direction: "steady",
      },
    ],
  },
  {
    id: "risk-complaints-3",
    riskId: "RA-022",
    title: "FOS overturn or redress escalation risk",
    description: "High overturn rates or redress escalations indicating poor quality final responses.",
    category: "reputational",
    subCategory: "Complaints",
    likelihood: 2,
    impact: 4,
    residualLikelihood: 2,
    residualImpact: 3,
    velocity: "slow",
    riskOwner: "Head of Compliance",
    businessUnit: "Compliance",
    process: "FOS escalation",
    controlCount: 4,
    controlEffectiveness: 3.4,
    status: "under_review",
    reviewFrequency: "quarterly",
    regulatoryCategory: ["DISP", "FOS"],
    reportableToFCA: false,
    consumerDutyRelevant: true,
    keyRiskIndicators: [
      {
        id: "kri-complaints-3",
        name: "FOS overturn rate",
        metric: "% of referrals upheld",
        threshold: { green: 15, amber: 25, red: 35 },
        currentValue: 22,
        direction: "steady",
      },
    ],
  },
  {
    id: "risk-complaints-4",
    riskId: "RA-023",
    title: "Vulnerable customer harm in complaints",
    description: "Complaints process fails to provide adequate support or adjustments for vulnerable customers.",
    category: "conduct",
    subCategory: "Vulnerable Customers",
    likelihood: 2,
    impact: 5,
    residualLikelihood: 2,
    residualImpact: 4,
    velocity: "medium",
    riskOwner: "Vulnerable Customer Lead",
    businessUnit: "Customer Experience",
    process: "Complaints handling",
    controlCount: 4,
    controlEffectiveness: 3,
    status: "open",
    reviewFrequency: "quarterly",
    regulatoryCategory: ["FG21/1", "Consumer Duty"],
    reportableToFCA: false,
    consumerDutyRelevant: true,
    keyRiskIndicators: [
      {
        id: "kri-complaints-4",
        name: "Vulnerable customer complaint outcomes",
        metric: "% resolved on time",
        threshold: { green: 95, amber: 90, red: 85 },
        currentValue: 87,
        direction: "down",
      },
    ],
  },
  {
    id: "risk-complaints-5",
    riskId: "RA-024",
    title: "Data quality gaps in complaints MI",
    description: "Incomplete or inconsistent MI undermines governance reporting and trend analysis.",
    category: "operational",
    subCategory: "MI & Reporting",
    likelihood: 3,
    impact: 3,
    residualLikelihood: 2,
    residualImpact: 2,
    velocity: "medium",
    riskOwner: "Compliance Reporting Lead",
    businessUnit: "Compliance",
    process: "Complaints MI",
    controlCount: 3,
    controlEffectiveness: 3.6,
    status: "under_review",
    reviewFrequency: "quarterly",
    regulatoryCategory: ["DISP 1.10", "Consumer Duty"],
    reportableToFCA: false,
    consumerDutyRelevant: true,
    keyRiskIndicators: [
      {
        id: "kri-complaints-5",
        name: "MI pack completeness",
        metric: "% of required fields captured",
        threshold: { green: 98, amber: 94, red: 90 },
        currentValue: 93,
        direction: "steady",
      },
    ],
  },
];
